#define THEORY_BASIC "Basic"
#define THEORY_NORMAL "Normal"
#define THEORY_ADVANCED "Advanced"
#define THEORY_COMPLEX "Complex"
#define THEORY_STELLAR "Stellar"
#define THEORY_BLUESPACE "Bluespace"
#define THEORY_ALIENT "Alien"
